[package]
name = "snorr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
hex = "0.4.3"
rand = "0.8.5"
schnorr_fun = "0.7.1"
sha2 = "0.9"

